# fly.toml app configuration file generated for saquota-blog-back-end on 2023-09-05T20:13:16-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "saquota-blog-back-end"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
